In [13]:
import numpy as np
from scipy.linalg import toeplitz, lu, inv
np.set_printoptions(precision=5)

In [11]:
K = toeplitz([2, -1, 0, 0, 0, 0])

In [16]:
P, L, U = lu(K)

In [18]:
P, L, U

(array([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]]),
 array([[ 1.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ],
        [-0.5    ,  1.     ,  0.     ,  0.     ,  0.     ,  0.     ],
        [ 0.     , -0.66667,  1.     ,  0.     ,  0.     ,  0.     ],
        [ 0.     ,  0.     , -0.75   ,  1.     ,  0.     ,  0.     ],
        [ 0.     ,  0.     ,  0.     , -0.8    ,  1.     ,  0.     ],
        [ 0.     ,  0.     ,  0.     ,  0.     , -0.83333,  1.     ]]),
 array([[ 2.     , -1.     ,  0.     ,  0.     ,  0.     ,  0.     ],
        [ 0.     ,  1.5    , -1.     ,  0.     ,  0.     ,  0.     ],
        [ 0.     ,  0.     ,  1.33333, -1.     ,  0.     ,  0.     ],
        [ 0.     ,  0.     ,  0.     ,  1.25   , -1.     ,  0.     ],
        [ 0.     ,  0.     ,  0.     ,  0.     ,  1.2    , -1.     ],
        [ 0.     ,  0.

In [17]:
inv(L)

array([[ 1.     ,  0.     ,  0.     ,  0.     , -0.     , -0.     ],
       [ 0.5    ,  1.     ,  0.     ,  0.     , -0.     , -0.     ],
       [ 0.33333,  0.66667,  1.     ,  0.     , -0.     , -0.     ],
       [ 0.25   ,  0.5    ,  0.75   ,  1.     , -0.     , -0.     ],
       [ 0.2    ,  0.4    ,  0.6    ,  0.8    ,  1.     , -0.     ],
       [ 0.16667,  0.33333,  0.5    ,  0.66667,  0.83333,  1.     ]])