In [1]:
import jax
import jax.numpy as np
from jax.scipy.linalg import lu

In [19]:
A = np.array([
    [1, 2, 2, 2],
    [2, 4, 6, 8],
    [3, 6, 8, 10],
])

In [20]:
lu(A)

(Array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]], dtype=float32),
 Array([[1.        , 0.        , 0.        ],
        [0.6666667 , 1.        , 0.        ],
        [0.33333334, 0.5       , 1.        ]], dtype=float32),
 Array([[ 3.0000000e+00,  6.0000000e+00,  8.0000000e+00,  1.0000000e+01],
        [ 0.0000000e+00, -1.1920929e-07,  6.6666651e-01,  1.3333330e+00],
        [ 0.0000000e+00,  0.0000000e+00, -1.0000000e+00, -2.0000000e+00]],      dtype=float32))