In [1]:
from jax import config
config.update("jax_enable_x64", True)

In [25]:
import numpy as np
import scipy
import jax
import jax.numpy as jnp

In [39]:
# generate a random symmetric matrix (to have real eigenvalues)
from jax import config
config.update("jax_enable_x64", True)

import numpy as np
import scipy
import jax
import jax.numpy as jnp

# generate a random symmetric matrix (to have real eigenvalues)
np.random.seed(42)
pre_A = np.random.normal(size=(3, 3))
A = pre_A.T @ pre_A
A = jnp.array(A)

# find the groundtruth eigenvalues
print(scipy.linalg.eigvals(A))

# this is f'(x)/f(x)
def newton_update(x, A):
    return 1 / jnp.trace(
        jnp.linalg.inv( x * jnp.eye(A.shape[0]) - A )
    )
    
# newton
x = jnp.array([1.])  # initial guess
for i in range(10):
    x = x - newton_update(x, A)
print(x)
pre_A = np.random.normal(size=(3, 3))
A = pre_A.T @ pre_A
A = jnp.array(A)
A

Array([[ 5.06025801,  0.78664234, -0.77628148],
       [ 0.78664234,  0.66290088, -0.39501919],
       [-0.77628148, -0.39501919,  0.69472676]], dtype=float64)

In [28]:
# find the groundtruth eigenvalues
scipy.linalg.eigvals(A)

array([5.34613967+0.j, 0.78854214+0.j, 0.28320384+0.j])

# Function for computing the determinant of xI - A

In [36]:
def det(x, A):
    return jnp.linalg.det(x * jnp.eye(A.shape[0]) - A)

# Automatic differention wrt x

In [37]:
automatic_grad = jax.grad(det)
automatic_grad(jnp.array([1.,]), A)

Array([-3.88274946], dtype=float64)

# Derived gradient wrt x

In [35]:
def derived_grad(x, A):
    return det(x, A) * jnp.trace(
        jnp.linalg.inv( x * jnp.eye(A.shape[0]) - A )
    )

In [18]:
derived_grad(jnp.array([1.,]), A)

Array(-3.88274946, dtype=float64)

# f'/f is the newton update (some stuff nicely cancels)

In [24]:
def newton_update(x, A):
    return 1 / jnp.trace(
        jnp.linalg.inv( x * jnp.eye(A.shape[0]) - A )
    )

In [31]:
x = jnp.array([1.,])
for i in range(10):
    x = x - newton_update(x, A)
print(x)

[0.78854214]


In [1]:
from jax import config
config.update("jax_enable_x64", True)

import numpy as np
import scipy
import jax
import jax.numpy as jnp

# generate a random symmetric matrix (to have real eigenvalues)
np.random.seed(42)
pre_A = np.random.normal(size=(3, 3))
A = pre_A.T @ pre_A
A = jnp.array(A)

# find the groundtruth eigenvalues
print(scipy.linalg.eigvals(A))

# this is f'(x)/f(x)
def newton_update(x, A):
    return 1 / jnp.trace(
        jnp.linalg.inv( x * jnp.eye(A.shape[0]) - A )
    )
    
# newton
x = jnp.array([1.])  # initial guess
for i in range(10):
    x = x - newton_update(x, A)
print(x)

[5.34613967+0.j 0.78854214+0.j 0.28320384+0.j]
[0.78854214]
