In [1]:
import numpy as np

In [3]:
A = np.array([
    [1, 0, 0],
    [0, 2, 0],
    [0, 0, 3]
])
b = np.array([
    [1],
    [1],
    [1]
])

In [6]:
b.T @ A

array([[1, 2, 3]])

In [8]:
A = np.random.normal(size=(4, 5))
B = np.random.normal(size=(4, 5))
one = np.ones((5, 1))

In [9]:
(A * B) @ one

array([[-1.11348334],
       [-2.79905244],
       [ 0.10522111],
       [ 2.87547701]])

In [10]:
A @ B.T

array([[-1.11348334,  1.45296456, -3.8542414 , -0.70083324],
       [ 0.09961436, -2.79905244,  3.30080192,  4.75460258],
       [ 3.62693477, -0.31432662,  0.10522111, -2.92594191],
       [ 0.50062153, -6.25978705,  1.77856271,  2.87547701]])